#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Additional flags
PREPROCESSOR_MACROS := DEBUG
INCLUDE_DIRS :=D:/NiVek/Firmware/NiVeKQC32/inc D:/NiVek/Firmware/NiVeKQC32/stm32f4periph/inc
LIBRARY_DIRS :=
LIBRARY_NAMES :=
ADDITIONAL_LINKER_INPUTS :=
MACOS_FRAMEWORKS :=

CFLAGS := -ggdb -ffunction-sections -O0 -std=gnu99 -gdwarf-2 -mthumb -fomit-frame-pointer -Wall -Wstrict-prototypes -fverbose-asm
CXXFLAGS := -ggdb -ffunction-sections -fno-exceptions -O0
ASFLAGS :=
LDFLAGS := -mthumb -nostartfiles -Wl,-gc-sections,-Map,output.map,--cref,--no-warn-mismatch
COMMONFLAGS :=

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain

ADDITIONAL_MAKE_FILES := stm32.mak
GENERATE_BIN_FILE := 1
